texto = input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(texto)))
print('Só tem espaços? {}'.format(texto.isspace()))
print('Só tem número? {}'.format(texto.isnumeric()))
print('Só tem letrs (alfabético)? {}'.format(texto.isalpha()))
print('É um número e/ou uma letra (alfanumérico)? {}'.format(texto.isalnum()))
print('Está maiúscula? {}'.format(texto.isupper()))
print('Está minúscula? {}'.format(texto.islower()))
print('Está capitalizada? {}'.format(texto.istitle()))