n1 = str(input('Digite um valor '))
print(n1)
print(type(n1))
n2 = int(input('Digite um valor '))
print(n2)
print(type(n2))
n3 = float(input('Digite um valor '))
print(n3)
print(type(n3))
n4 = bool(input('Digite um valor '))
print(n4)
print(type(n4))